services:
  agenda-manager-api:
    image: agenda-manager-api
    container_name: agenda-manager-api
    build:
      context: .
      dockerfile: src/WebApi/Dockerfile
    ports:
      - "7000:443"
    environment:
      - ASPNETCORE_URLS=https://+:443
      - ASPNETCORE_Kestrel__Certificates__Default__Password=Test1234!
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - ASPNETCORE_Environment=Development
      - ConnectionStrings__DefaultConnection=Server=agenda-manager-db;Port=5432;Database=AgendaManager;User ID=postgres;Password=postgres;
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://agenda-manager-jeager:4317
    depends_on:
      - agenda-manager-db
      - agenda-manager-seq
      - agenda-manager-rabbitmq
    volumes:
      - ./.containers/https:/https
    networks:
      - agenda-net

  agenda-manager-db:
    image: postgres:latest
    restart: always
    container_name: agenda-manager-db
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=AgendaManager
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - TZ=UTC
    volumes:
      - ./.containers/postgresql:/var/lib/postgresql/data
    networks:
      - agenda-net
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  agenda-manager-seq:
    image: datalust/seq:latest
    container_name: agenda-manager-serilog-seq
    restart: always
    environment:
      - ACCEPT_EULA=Y
    ports:
      - "5341:5341"
      - "8081:80"
    networks:
      - agenda-net

  agenda-manager-jeager:
    image: jaegertracing/all-in-one:latest
    container_name: agenda-manager-jeager
    restart: always
    ports:
      - "4317:4317"
      - "4318:4318"
      - "16686:16686"
    depends_on:
      - agenda-manager-api
    networks:
      - agenda-net

  agenda-manager-rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: agenda-manager-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    volumes:
      - ./.containers/rabbitmq:/var/lib/rabbitmq
    networks:
      - agenda-net
    restart: unless-stopped

networks:
  agenda-net:
    driver: bridge
